<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tasked_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tasked_module':
      return t('text string mods');
  }
}

/**
 * Implements hook_theme().
 */
function tasked_module_theme($existing, $type, $theme, $path) {
  $variables = [
    'tasked_module' => [
      'variables' => [
        'source_text' => NULL,
      ],
      'template' => 'tasked_module',
    ],
  ];
  return $variables;
}

/**
 * Template preprocess function for Tasked Module.
 *
 * @param array $variables
 *   An associative array containing:
 *   - source_text
 */
function template_preprocess_tasked_module(&$variables) {
  $punctuation = array('. ', '! ', '? ', '... ', ': ', '; ');
  for ($i = 0; $i < count($variables['source_text']); $i++) {
    $big_text = explode('. ', $variables['source_text'][$i]);
    for ($j = 0; $j < count($big_text) - 1; $j++) {
      $big_text[$j] .= $punctuation[floor(mt_rand(0, count($punctuation) - 1))];
    }
    $variables['source_text'][$i] = implode('', $big_text);
  }
}