tasked_module.settings:
  type: config_object
  label: 'Tasked Module settings'
  mapping:
    tasked_module:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Tasked Module generator page title:'
        source_text:
          type: text
          label: 'Source text for tasked module generation:'
block.settings.tasked_module_block:
  type: block_settings
  label: 'Tasked module block'
  mapping:
    tasked_module_block_settings:
      type: text
      label: 'Tasked module block settings'
